### ISSUE TITLE
Question - How to add environment variables to your Deployment?

### ISSUE THREAD

**Issue by jeffdeville** [previousnext/terraform-provider-k8s#4]
I need to get some secrets into a deployment. Is that doable w/ your fork?  Thanks!

**Comment by nickschuch** [comment]
Absolutely! :)

Variables can be set like the below:

```
resource "k8s_deployment" "example" {
  name      = "example"
  namespace = "default"

  labels {
    app = "example"
  }

  container {
    name  = "container1"
    image = "foo/bar:latest"

    requests {
      cpu    = "100m"
      memory = "40Mi"
    }

    limits {
      cpu    = "100m"
      memory = "40Mi"
    }

    env {
      name  = "FOO"
      value = "bar"
    }
  }
}
```

If you looking for something like this:

https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

I would be very happy to add it for you :)

**Comment by jeffdeville** [comment]
Hey @nickschuch, thanks!  I think just environment variables will work for the time being.
